# Generated by Django 3.2.9 on 2021-12-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='Profile'),
        ),
    ]
